export const SCHEMA = {
  // ── Administrative Hierarchy ─────────────────────────────
  city: {
    label: 'City / Province', icon: '🏙️', color: '#0A3D91', group: 'Core',
    columns: [
      { key: 'id',         label: 'ID',         type: 'uuid',     pk: true },
      { key: 'name',       label: 'Name',       type: 'text',     required: true, example: 'City of Kigali' },
      { key: 'country',    label: 'Country',    type: 'text',     required: true, example: 'Rwanda', default: 'Rwanda' },
      { key: 'area_km2',   label: 'Area (km²)', type: 'integer',  example: '730' },
      { key: 'updated_at', label: 'Updated At', type: 'datetime', auto: true },
    ],
    display: ['name', 'country', 'area_km2'],
  },

  district: {
    label: 'District', icon: '📍', color: '#1251C5', group: 'Core',
    columns: [
      { key: 'id',       label: 'ID',              type: 'uuid',    pk: true },
      { key: 'city_id',  label: 'City / Province', type: 'fk',      ref: 'city',     required: true },
      { key: 'code',     label: 'Code',            type: 'text',    required: true,  example: 'KIG-GAS' },
      { key: 'name',     label: 'Name',            type: 'text',    required: true,  example: 'Gasabo' },
      { key: 'area_km2', label: 'Area (km²)',      type: 'decimal', example: '429' },
    ],
    display: ['name', 'city_id', 'code', 'area_km2'],
  },

  sector: {
    label: 'Sector', icon: '🏘️', color: '#1A7A3C', group: 'Core',
    columns: [
      { key: 'id',          label: 'ID',             type: 'uuid', pk: true },
      { key: 'city_id',     label: 'City / Province',type: 'fk',   ref: 'city',     required: true },
      { key: 'district_id', label: 'District',       type: 'fk',   ref: 'district', required: true },
      { key: 'code',        label: 'Code',           type: 'text', required: true,  example: 'GAS-REM' },
      { key: 'name',        label: 'Name',           type: 'text', required: true,  example: 'Remera' },
    ],
    display: ['name', 'district_id', 'code'],
  },

  cell: {
    label: 'Cell', icon: '🔷', color: '#E8B400', group: 'Core',
    columns: [
      { key: 'id',        label: 'ID',     type: 'uuid', pk: true },
      { key: 'sector_id', label: 'Sector', type: 'fk',   ref: 'sector', required: true },
      { key: 'code',      label: 'Code',   type: 'text', required: true, example: 'GAS-REM-C01' },
      { key: 'name',      label: 'Name',   type: 'text', required: true, example: 'Kanogo' },
    ],
    display: ['name', 'sector_id', 'code'],
  },

  village: {
    label: 'Village', icon: '🏡', color: '#25A356', group: 'Core',
    columns: [
      { key: 'id',      label: 'ID',   type: 'uuid', pk: true },
      { key: 'cell_id', label: 'Cell', type: 'fk',   ref: 'cell', required: true },
      { key: 'code',    label: 'Code', type: 'text', required: true, example: 'GAS-REM-C01-V01' },
      { key: 'name',    label: 'Name', type: 'text', required: true, example: 'Village 1 (Kanogo)' },
    ],
    display: ['name', 'cell_id', 'code'],
  },

  // ── Stats Tables ─────────────────────────────────────────
  demographic: {
    label: 'Demographic', icon: '👥', color: '#a78bfa', group: 'Demographics',
    columns: [
      { key: 'id',                      label: 'ID',                  type: 'uuid',    pk: true },
      { key: 'city_id',                 label: 'City / Province',     type: 'fk',      ref: 'city' },
      { key: 'district_id',             label: 'District',            type: 'fk',      ref: 'district',  required: true },
      { key: 'sector_id',               label: 'Sector',              type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                 label: 'Cell',                type: 'fk',      ref: 'cell' },
      { key: 'village_id',              label: 'Village',             type: 'fk',      ref: 'village',   required: true },
      { key: 'year',                    label: 'Year',                type: 'integer',  required: true,  example: '2024' },
      { key: 'total_population',        label: 'Total Population',    type: 'integer',  example: '644887' },
      { key: 'male_population',         label: 'Male Population',     type: 'integer',  example: '310000' },
      { key: 'female_population',       label: 'Female Population',   type: 'integer',  example: '334887' },
      { key: 'density_per_km2',         label: 'Density (per km²)',   type: 'decimal',  example: '1503.2' },
      { key: 'youth_population_16_30',  label: 'Youth Pop. (16–30)',  type: 'integer',  example: '282898' },
      { key: 'youth_share_pct',         label: 'Youth Share (%)',     type: 'decimal',  example: '43.90' },
      { key: 'working_age_pop_15_64',   label: 'Working Age Pop.',    type: 'integer',  example: '1205000' },
      { key: 'total_dependency_ratio',  label: 'Dependency Ratio',    type: 'decimal',  example: '54.0' },
      { key: 'number_of_households',    label: 'Households',          type: 'integer',  example: '493000' },
      { key: 'avg_household_size',      label: 'Avg. HH Size',        type: 'decimal',  example: '3.8' },
      { key: 'live_births',             label: 'Live Births',         type: 'integer',  example: '24641' },
      { key: 'crude_birth_rate',        label: 'Birth Rate (/1K)',     type: 'decimal',  example: '25.5' },
      { key: 'registered_deaths',       label: 'Registered Deaths',   type: 'integer',  example: '1957' },
      { key: 'crude_death_rate',        label: 'Death Rate (/1K)',     type: 'decimal',  example: '2.1' },
      { key: 'registered_marriages',    label: 'Marriages',           type: 'integer',  example: '5543' },
      { key: 'annual_growth_rate_pct',  label: 'Growth Rate (%)',     type: 'decimal',  example: '4.42' },
      { key: 'created_at',              label: 'Created At',          type: 'datetime', auto: true },
      { key: 'updated_at',              label: 'Updated At',          type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'total_population', 'youth_share_pct', 'annual_growth_rate_pct'],
  },

  household_poverty: {
    label: 'Household & Poverty', icon: '🏘️', color: '#f5a623', group: 'Society',
    columns: [
      { key: 'id',                            label: 'ID',                    type: 'uuid',    pk: true },
      { key: 'city_id',                       label: 'City / Province',       type: 'fk',      ref: 'city' },
      { key: 'district_id',                   label: 'District',              type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                     label: 'Sector',                type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                       label: 'Cell',                  type: 'fk',      ref: 'cell' },
      { key: 'village_id',                    label: 'Village',               type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                          label: 'Year',                  type: 'integer',  required: true, example: '2024' },
      { key: 'poverty_headcount_pct',         label: 'Poverty Headcount (%)', type: 'decimal',  example: '14.90' },
      { key: 'extreme_poverty_pct',           label: 'Extreme Poverty (%)',   type: 'decimal',  example: '4.20' },
      { key: 'gini_coefficient',              label: 'Gini Coefficient',      type: 'decimal',  example: '0.420' },
      { key: 'avg_monthly_expenditure_rwf',   label: 'Avg. Monthly Exp. (RwF)', type: 'decimal', example: '185000.00' },
      { key: 'food_expenditure_share_pct',    label: 'Food Exp. Share (%)',   type: 'decimal',  example: '38.00' },
      { key: 'housing_expenditure_share_pct', label: 'Housing Exp. Share (%)',type: 'decimal',  example: '22.00' },
      { key: 'electricity_access_pct',        label: 'Electricity Access (%)',type: 'decimal',  example: '82.00' },
      { key: 'improved_water_access_pct',     label: 'Improved Water (%)',    type: 'decimal',  example: '88.50' },
      { key: 'health_insurance_hh_pct',       label: 'Health Insurance (%HH)',type: 'decimal',  example: '86.50' },
      { key: 'created_at',                    label: 'Created At',            type: 'datetime', auto: true },
      { key: 'updated_at',                    label: 'Updated At',            type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'poverty_headcount_pct', 'gini_coefficient', 'avg_monthly_expenditure_rwf'],
  },

  youth_education: {
    label: 'Youth & Education', icon: '📚', color: '#a78bfa', group: 'Society',
    columns: [
      { key: 'id',                        label: 'ID',                    type: 'uuid',    pk: true },
      { key: 'city_id',                   label: 'City / Province',       type: 'fk',      ref: 'city' },
      { key: 'district_id',               label: 'District',              type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                 label: 'Sector',                type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                   label: 'Cell',                  type: 'fk',      ref: 'cell' },
      { key: 'village_id',                label: 'Village',               type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                      label: 'Year',                  type: 'integer',  required: true, example: '2024' },
      { key: 'survey_wave',               label: 'Survey Wave',           type: 'text',     example: 'EICV7' },
      { key: 'youth_population_16_30',    label: 'Youth Pop. (16–30)',    type: 'integer',  example: '282898' },
      { key: 'literacy_rate_pct',         label: 'Literacy Rate (%)',     type: 'decimal',  example: '93.50' },
      { key: 'numeracy_rate_pct',         label: 'Numeracy Rate (%)',     type: 'decimal',  example: '95.30' },
      { key: 'computer_literacy_pct',     label: 'Computer Literacy (%)', type: 'decimal',  example: '36.10' },
      { key: 'internet_usage_pct',        label: 'Internet Usage (%)',    type: 'decimal',  example: '53.90' },
      { key: 'higher_education_pct',      label: 'Higher Education (%)',  type: 'decimal',  example: '14.60' },
      { key: 'tvet_pct',                  label: 'TVET (%)',              type: 'decimal',  example: '6.50' },
      { key: 'private_school_share_pct',  label: 'Private School (%)',    type: 'decimal',  example: '39.20' },
      { key: 'wpr_total_pct',             label: 'Youth WPR (%)',         type: 'decimal',  example: '63.70' },
      { key: 'health_insurance_pct',      label: 'Health Insurance (%)',  type: 'decimal',  example: '90.40' },
      { key: 'youth_migrants',            label: 'Youth Migrants',        type: 'integer',  example: '446000' },
      { key: 'migration_work_reason_pct', label: 'Migration for Work (%)',type: 'decimal',  example: '55.10' },
      { key: 'created_at',                label: 'Created At',            type: 'datetime', auto: true },
      { key: 'updated_at',                label: 'Updated At',            type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'literacy_rate_pct', 'computer_literacy_pct', 'wpr_total_pct'],
  },

  agriculture: {
    label: 'Agriculture', icon: '🌱', color: '#4ade80', group: 'Environment',
    columns: [
      { key: 'id',                          label: 'ID',                    type: 'uuid',    pk: true },
      { key: 'city_id',                     label: 'City / Province',       type: 'fk',      ref: 'city' },
      { key: 'district_id',                 label: 'District',              type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                   label: 'Sector',                type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                     label: 'Cell',                  type: 'fk',      ref: 'cell' },
      { key: 'village_id',                  label: 'Village',               type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                        label: 'Year',                  type: 'integer',  required: true, example: '2025' },
      { key: 'season',                      label: 'Season',                type: 'select',   options: ['A', 'B', 'C'], required: true },
      { key: 'agri_land_000ha',             label: 'Agri Land (000 Ha)',    type: 'decimal',  example: '21.700' },
      { key: 'physical_cultivated_000ha',   label: 'Cultivated (000 Ha)',   type: 'decimal',  example: '18.100' },
      { key: 'irrigated_land_ha',           label: 'Irrigated (Ha)',        type: 'decimal',  example: '618.0' },
      { key: 'erosion_control_ha',          label: 'Erosion Control (Ha)',  type: 'decimal',  example: '13765.0' },
      { key: 'organic_fertilizer_use_pct',  label: 'Organic Fert. (%)',     type: 'decimal',  example: '85.70' },
      { key: 'inorganic_fertilizer_use_pct',label: 'Inorganic Fert. (%)',   type: 'decimal',  example: '52.60' },
      { key: 'improved_seeds_use_pct',      label: 'Improved Seeds (%)',    type: 'decimal',  example: '42.50' },
      { key: 'cereal_production_mt',        label: 'Cereal Production (MT)',type: 'integer',  example: '6501' },
      { key: 'tuber_production_mt',         label: 'Tuber Production (MT)', type: 'integer',  example: '23580' },
      { key: 'maize_yield_kg_ha',           label: 'Maize Yield (Kg/Ha)',   type: 'decimal',  example: '1582.0' },
      { key: 'cassava_yield_kg_ha',         label: 'Cassava Yield (Kg/Ha)', type: 'decimal',  example: '12694.0' },
      { key: 'created_at',                  label: 'Created At',            type: 'datetime', auto: true },
      { key: 'updated_at',                  label: 'Updated At',            type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'season', 'cereal_production_mt', 'maize_yield_kg_ha'],
  },

  business_enterprise: {
    label: 'Business & Enterprise', icon: '🏢', color: '#f5a623', group: 'Economy',
    columns: [
      { key: 'id',                        label: 'ID',                         type: 'uuid',    pk: true },
      { key: 'city_id',                   label: 'City / Province',            type: 'fk',      ref: 'city' },
      { key: 'district_id',               label: 'District',                   type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                 label: 'Sector',                     type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                   label: 'Cell',                       type: 'fk',      ref: 'cell' },
      { key: 'village_id',                label: 'Village',                    type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                      label: 'Year',                       type: 'integer',  required: true, example: '2023' },
      { key: 'total_businesses',          label: 'Total Businesses',           type: 'integer',  example: '64884' },
      { key: 'micro_enterprises',         label: 'Micro (1–3 workers)',        type: 'integer',  example: '55459' },
      { key: 'small_enterprises',         label: 'Small (4–30 workers)',       type: 'integer',  example: '6843' },
      { key: 'medium_enterprises',        label: 'Medium (31–100)',            type: 'integer',  example: '684' },
      { key: 'large_enterprises',         label: 'Large (100+)',               type: 'integer',  example: '255' },
      { key: 'formal_enterprises',        label: 'Formal Enterprises',        type: 'integer',  example: '12022' },
      { key: 'informal_enterprises',      label: 'Informal Enterprises',      type: 'integer',  example: '51219' },
      { key: 'registered_investment_usd', label: 'Registered Investment (USD)',type: 'bigint',   example: '3270539015' },
      { key: 'jobs_to_be_created',        label: 'Jobs to be Created',        type: 'integer',  example: '51635' },
      { key: 'business_survival_3yr_pct', label: '3yr Survival Rate (%)',     type: 'decimal',  example: '19.30' },
      { key: 'created_at',                label: 'Created At',                type: 'datetime', auto: true },
      { key: 'updated_at',                label: 'Updated At',                type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'total_businesses', 'formal_enterprises', 'registered_investment_usd'],
  },

  financial_inclusion: {
    label: 'Financial Inclusion', icon: '💳', color: '#a78bfa', group: 'Economy',
    columns: [
      { key: 'id',                                label: 'ID',                    type: 'uuid',    pk: true },
      { key: 'city_id',                           label: 'City / Province',       type: 'fk',      ref: 'city' },
      { key: 'district_id',                       label: 'District',              type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                         label: 'Sector',                type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                           label: 'Cell',                  type: 'fk',      ref: 'cell' },
      { key: 'village_id',                        label: 'Village',               type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                              label: 'Year',                  type: 'integer',  required: true, example: '2024' },
      { key: 'banked_population_pct',             label: 'Banked Population (%)', type: 'decimal',  example: '46.00' },
      { key: 'bank_branches',                     label: 'Bank Branches',         type: 'integer',  example: '285' },
      { key: 'atm_per_100k_adults',               label: 'ATMs per 100K Adults',  type: 'decimal',  example: '42.00' },
      { key: 'mobile_money_penetration_pct',      label: 'Mobile Money (%)',       type: 'decimal',  example: '78.00' },
      { key: 'mobile_money_transaction_vol',      label: 'MoMo Volume (RwF)',      type: 'bigint',   example: '220876619286' },
      { key: 'digital_payment_adoption_pct',      label: 'Digital Payment (%)',    type: 'decimal',  example: '62.00' },
      { key: 'private_sector_credit_growth_pct',  label: 'Credit Growth (%)',      type: 'decimal',  example: '36.52' },
      { key: 'lending_rate_pct',                  label: 'Lending Rate (%)',       type: 'decimal',  example: '16.20' },
      { key: 'deposit_rate_pct',                  label: 'Deposit Rate (%)',       type: 'decimal',  example: '7.80' },
      { key: 'microfinance_institutions',         label: 'MFIs Active',            type: 'integer',  example: '180' },
      { key: 'saccos',                            label: 'SACCOs',                 type: 'integer',  example: '62' },
      { key: 'created_at',                        label: 'Created At',             type: 'datetime', auto: true },
      { key: 'updated_at',                        label: 'Updated At',             type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'banked_population_pct', 'mobile_money_penetration_pct', 'lending_rate_pct'],
  },

  labor_market: {
    label: 'Labor Market', icon: '⚙️', color: '#f5a623', group: 'Society',
    columns: [
      { key: 'id',                              label: 'ID',                      type: 'uuid',    pk: true },
      { key: 'city_id',                         label: 'City / Province',         type: 'fk',      ref: 'city' },
      { key: 'district_id',                     label: 'District',                type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                       label: 'Sector',                  type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                         label: 'Cell',                    type: 'fk',      ref: 'cell' },
      { key: 'village_id',                      label: 'Village',                 type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                            label: 'Year',                    type: 'integer',  required: true, example: '2023' },
      { key: 'total_enterprise_employment',     label: 'Total Employment',        type: 'integer',  example: '295672' },
      { key: 'formal_workers',                  label: 'Formal Workers',          type: 'integer',  example: '204987' },
      { key: 'informal_workers',                label: 'Informal Workers',        type: 'integer',  example: '88739' },
      { key: 'formal_share_pct',                label: 'Formal Share (%)',        type: 'decimal',  example: '69.80' },
      { key: 'female_workers',                  label: 'Female Workers',          type: 'integer',  example: '130024' },
      { key: 'female_share_pct',                label: 'Female Share (%)',        type: 'decimal',  example: '44.00' },
      { key: 'lfpr_total_pct',                  label: 'LFPR Total (%)',          type: 'decimal',  example: '71.50' },
      { key: 'youth_wpr_total_pct',             label: 'Youth WPR (%)',           type: 'decimal',  example: '63.70' },
      { key: 'unemployment_rate_pct',           label: 'Unemployment (%)',        type: 'decimal',  example: '16.30' },
      { key: 'youth_unemployment_pct',          label: 'Youth Unemployment (%)',  type: 'decimal',  example: '33.30' },
      { key: 'services_employment_share_pct',   label: 'Services Share (%)',      type: 'decimal',  example: '97.90' },
      { key: 'created_at',                      label: 'Created At',              type: 'datetime', auto: true },
      { key: 'updated_at',                      label: 'Updated At',              type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'total_enterprise_employment', 'formal_share_pct', 'unemployment_rate_pct'],
  },

  infrastructure: {
    label: 'Infrastructure', icon: '🔌', color: '#4ade80', group: 'Environment',
    columns: [
      { key: 'id',                          label: 'ID',                    type: 'uuid',    pk: true },
      { key: 'city_id',                     label: 'City / Province',       type: 'fk',      ref: 'city' },
      { key: 'district_id',                 label: 'District',              type: 'fk',      ref: 'district', required: true },
      { key: 'sector_id',                   label: 'Sector',                type: 'fk',      ref: 'sector' },
      { key: 'cell_id',                     label: 'Cell',                  type: 'fk',      ref: 'cell' },
      { key: 'village_id',                  label: 'Village',               type: 'fk',      ref: 'village',  required: true },
      { key: 'year',                        label: 'Year',                  type: 'integer',  required: true, example: '2024' },
      { key: 'electricity_customers',       label: 'Electricity Customers', type: 'integer',  example: '327776' },
      { key: 'electricity_share_of_hh_pct', label: 'Electrification (%HH)', type: 'decimal',  example: '66.50' },
      { key: 'water_customers',             label: 'Water Customers',       type: 'integer',  example: '180695' },
      { key: 'water_production_m3_annual',  label: 'Water Production (m³)', type: 'bigint',   example: '37616985' },
      { key: 'paved_roads_national_km',     label: 'Paved Roads (km)',      type: 'decimal',  example: '36.36' },
      { key: 'accommodation_facilities',    label: 'Hotel Facilities',      type: 'integer',  example: '277' },
      { key: 'hotel_rooms',                 label: 'Hotel Rooms',           type: 'integer',  example: '5450' },
      { key: 'avg_commute_minutes',         label: 'Avg. Commute (min)',    type: 'decimal',  example: '38.0' },
      { key: 'open_defecation_free_pct',    label: 'ODF Rate (%)',          type: 'decimal',  example: '98.50' },
      { key: 'created_at',                  label: 'Created At',            type: 'datetime', auto: true },
      { key: 'updated_at',                  label: 'Updated At',            type: 'datetime', auto: true },
    ],
    display: ['city_id', 'district_id', 'sector_id', 'cell_id', 'village_id', 'year', 'electricity_customers', 'water_customers', 'paved_roads_national_km'],
  },

  // ── Remaining tables unchanged from original SCHEMA ──────
  civil_registration: {
    label: 'Civil Registration', icon: '📋', color: '#5b8dee', group: 'Demographics',
    columns: [
      { key: 'id',                      label: 'ID',                      type: 'uuid',    pk: true },
      { key: 'district_id',             label: 'District',                type: 'fk',      ref: 'district', required: true },
      { key: 'year',                    label: 'Year',                    type: 'integer',  required: true, example: '2024' },
      { key: 'live_births_total',       label: 'Live Births (Total)',      type: 'integer',  example: '24641' },
      { key: 'live_births_male',        label: 'Live Births (Male)',       type: 'integer',  example: '12488' },
      { key: 'live_births_female',      label: 'Live Births (Female)',     type: 'integer',  example: '12153' },
      { key: 'sex_ratio_at_birth',      label: 'Sex Ratio at Birth',       type: 'decimal',  example: '102.8' },
      { key: 'born_same_district_pct',  label: 'Born Same District (%)',   type: 'decimal',  example: '65.50' },
      { key: 'registered_deaths_total', label: 'Registered Deaths',        type: 'integer',  example: '1957' },
      { key: 'deaths_in_facility_pct',  label: 'Deaths in Facility (%)',   type: 'decimal',  example: '58.20' },
      { key: 'registered_marriages',    label: 'Registered Marriages',     type: 'integer',  example: '5543' },
      { key: 'crude_birth_rate',        label: 'Crude Birth Rate (/1K)',   type: 'decimal',  example: '25.5' },
      { key: 'crude_death_rate',        label: 'Crude Death Rate (/1K)',   type: 'decimal',  example: '2.1' },
    ],
    display: ['district_id', 'year', 'live_births_total', 'registered_deaths_total', 'registered_marriages'],
  },

  economic_indicator: {
    label: 'Economic Indicators', icon: '📈', color: '#2dd4a0', group: 'Economy',
    columns: [
      { key: 'id',                    label: 'ID',                   type: 'uuid',    pk: true },
      { key: 'district_id',           label: 'District',             type: 'fk',      ref: 'district', required: true },
      { key: 'year',                  label: 'Year',                 type: 'integer',  required: true, example: '2024' },
      { key: 'gdp_rwf_billion',       label: 'GDP / OSR (RwF Bn)',   type: 'decimal',  example: '44.492' },
      { key: 'gdp_growth_rate_pct',   label: 'GDP Growth (%)',       type: 'decimal',  example: '16.70' },
      { key: 'kigali_gdp_share_pct',  label: 'Kigali GDP Share (%)', type: 'decimal',  example: '35.00' },
      { key: 'gdp_per_capita_usd',    label: 'GDP per Capita (USD)', type: 'decimal',  example: '1800.00' },
      { key: 'services_share_pct',    label: 'Services Share (%)',   type: 'decimal',  example: '68.00' },
      { key: 'industry_share_pct',    label: 'Industry Share (%)',   type: 'decimal',  example: '18.00' },
      { key: 'inflation_rate_pct',    label: 'Inflation Rate (%)',   type: 'decimal',  example: '2.10' },
      { key: 'food_inflation_pct',    label: 'Food Inflation (%)',   type: 'decimal',  example: '1.80' },
      { key: 'cpi_index',             label: 'CPI Index',            type: 'decimal',  example: '100.00' },
      { key: 'ppi_index',             label: 'PPI Index',            type: 'decimal',  example: '98.00' },
    ],
    display: ['district_id', 'year', 'gdp_rwf_billion', 'gdp_growth_rate_pct', 'inflation_rate_pct'],
  },

  revenue_finance: {
    label: 'Revenue & Finance', icon: '💰', color: '#4ade80', group: 'Economy',
    columns: [
      { key: 'id',                          label: 'ID',                      type: 'uuid',    pk: true },
      { key: 'city_id',                     label: 'City',                    type: 'fk',      ref: 'city', required: true },
      { key: 'fiscal_year',                 label: 'Fiscal Year',             type: 'text',     required: true, example: 'FY2023-24' },
      { key: 'budget_target_rwf',           label: 'Budget Target (RwF)',     type: 'bigint',   example: '41092698721' },
      { key: 'actual_collection_rwf',       label: 'Actual Collection (RwF)', type: 'bigint',   example: '44492170572' },
      { key: 'achievement_rate_pct',        label: 'Achievement Rate (%)',    type: 'decimal',  example: '108.00' },
      { key: 'yoy_growth_pct',              label: 'YoY Growth (%)',          type: 'decimal',  example: '16.70' },
      { key: 'total_tax_revenue_rwf',       label: 'Tax Revenue (RwF)',       type: 'bigint',   example: '35644139129' },
      { key: 'rental_income_tax_rwf',       label: 'Rental Income Tax (RwF)', type: 'bigint',   example: '13228000999' },
      { key: 'immovable_property_tax_rwf',  label: 'Property Tax (RwF)',      type: 'bigint',   example: '12338215613' },
      { key: 'trading_licence_rwf',         label: 'Trading Licence (RwF)',   type: 'bigint',   example: '5421794068' },
      { key: 'property_sales_tax_rwf',      label: 'Property Sales Tax (RwF)',type: 'bigint',   example: '4656128449' },
      { key: 'total_other_revenue_rwf',     label: 'Other Revenue (RwF)',     type: 'bigint',   example: '8848031443' },
      { key: 'cleaning_fees_rwf',           label: 'Cleaning Fees (RwF)',     type: 'bigint',   example: '2009122173' },
    ],
    display: ['fiscal_year', 'actual_collection_rwf', 'achievement_rate_pct', 'yoy_growth_pct'],
  },

  rssb_stats: {
    label: 'RSSB Stats', icon: '🏥', color: '#5b8dee', group: 'Society',
    columns: [
      { key: 'id',                        label: 'ID',                          type: 'uuid',    pk: true },
      { key: 'district_id',               label: 'District',                    type: 'fk',      ref: 'district', required: true },
      { key: 'fiscal_year',               label: 'Fiscal Year',                 type: 'text',     required: true, example: 'FY2024-25' },
      { key: 'active_members_total',      label: 'Active Members',              type: 'integer',  example: '288939' },
      { key: 'active_members_male',       label: 'Active Male',                 type: 'integer',  example: '206289' },
      { key: 'active_members_female',     label: 'Active Female',               type: 'integer',  example: '82650' },
      { key: 'passive_members_total',     label: 'Passive Members',             type: 'integer',  example: '507462' },
      { key: 'contributing_institutions', label: 'Contributing Institutions',   type: 'integer',  example: '4079' },
      { key: 'total_contributions_rwf',   label: 'Total Contributions (RwF)',   type: 'bigint',   example: '112748070454' },
      { key: 'medical_scheme_total',      label: 'Medical Scheme Total',        type: 'integer',  example: '68635' },
      { key: 'medical_affiliates',        label: 'Medical Affiliates',          type: 'integer',  example: '23943' },
      { key: 'medical_dependents',        label: 'Medical Dependents',          type: 'integer',  example: '44692' },
      { key: 'cbhi_mutuelles',            label: 'CBHI Mutuelles',              type: 'integer',  example: '489434' },
    ],
    display: ['district_id', 'fiscal_year', 'active_members_total', 'total_contributions_rwf', 'cbhi_mutuelles'],
  },

  tourism: {
    label: 'Tourism', icon: '✈️', color: '#2dd4a0', group: 'Environment',
    columns: [
      { key: 'id',                      label: 'ID',                      type: 'uuid',    pk: true },
      { key: 'city_id',                 label: 'City',                    type: 'fk',      ref: 'city', required: true },
      { key: 'district_id',             label: 'District',                type: 'fk',      ref: 'district' },
      { key: 'year',                    label: 'Year',                    type: 'integer',  required: true, example: '2024' },
      { key: 'total_park_visitors',     label: 'Total Park Visitors',     type: 'integer',  example: '150525' },
      { key: 'volcanoes_np_visitors',   label: 'Volcanoes NP',            type: 'integer',  example: '53197' },
      { key: 'akagera_np_visitors',     label: 'Akagera NP',              type: 'integer',  example: '67661' },
      { key: 'nyungwe_np_visitors',     label: 'Nyungwe NP',              type: 'integer',  example: '29667' },
      { key: 'rwandan_residents',       label: 'Rwandan Residents',       type: 'integer',  example: '45763' },
      { key: 'foreign_residents',       label: 'Foreign Residents',       type: 'integer',  example: '8491' },
      { key: 'foreign_visitors',        label: 'Foreign Visitors',        type: 'integer',  example: '96271' },
      { key: 'accommodation_facilities',label: 'Accommodation Facilities',type: 'integer',  example: '277' },
      { key: 'hotel_rooms',             label: 'Hotel Rooms',             type: 'integer',  example: '5450' },
    ],
    display: ['year', 'total_park_visitors', 'foreign_visitors', 'accommodation_facilities', 'hotel_rooms'],
  },

  crime_safety: {
    label: 'Crime & Safety', icon: '🛡️', color: '#f05252', group: 'Safety',
    columns: [
      { key: 'id',                    label: 'ID',              type: 'uuid',    pk: true },
      { key: 'city_id',               label: 'City',            type: 'fk',      ref: 'city', required: true },
      { key: 'year',                  label: 'Year',            type: 'integer',  required: true, example: '2024' },
      { key: 'total_crimes',          label: 'Total Crimes',    type: 'integer',  example: '20363' },
      { key: 'national_total_crimes', label: 'National Total',  type: 'integer',  example: '77322' },
      { key: 'kigali_share_pct',      label: 'Kigali Share (%)',type: 'decimal',  example: '26.30' },
      { key: 'theft',                 label: 'Theft',           type: 'integer',  example: '5911' },
      { key: 'assault_battery',       label: 'Assault & Battery',type: 'integer', example: '4389' },
      { key: 'breach_of_trust',       label: 'Breach of Trust', type: 'integer',  example: '2283' },
      { key: 'fraud',                 label: 'Fraud',           type: 'integer',  example: '1398' },
      { key: 'child_defilement',      label: 'Child Defilement',type: 'integer',  example: '835' },
      { key: 'narcotic_drugs',        label: 'Narcotic Drugs',  type: 'integer',  example: '991' },
      { key: 'damaging_property',     label: 'Damaging Property',type: 'integer', example: '893' },
    ],
    display: ['year', 'total_crimes', 'kigali_share_pct', 'theft', 'fraud'],
  },

  disaster: {
    label: 'Disasters', icon: '⚠️', color: '#f5a623', group: 'Safety',
    columns: [
      { key: 'id',                    label: 'ID',                    type: 'uuid',   pk: true },
      { key: 'district_id',           label: 'District',              type: 'fk',     ref: 'district', required: true },
      { key: 'fiscal_year',           label: 'Fiscal Year',           type: 'text',   required: true, example: 'FY2023-24' },
      { key: 'flood_deaths',          label: 'Flood Deaths',          type: 'integer', example: '1' },
      { key: 'fire_deaths',           label: 'Fire Deaths',           type: 'integer', example: '6' },
      { key: 'house_collapse_deaths', label: 'House Collapse Deaths', type: 'integer', example: '4' },
      { key: 'landslide_deaths',      label: 'Landslide Deaths',      type: 'integer', example: '3' },
      { key: 'lightning_deaths',      label: 'Lightning Deaths',      type: 'integer', example: '0' },
      { key: 'rainstorm_deaths',      label: 'Rainstorm Deaths',      type: 'integer', example: '0' },
      { key: 'mine_disaster_deaths',  label: 'Mine Disaster Deaths',  type: 'integer', example: '0' },
      { key: 'strong_wind_deaths',    label: 'Strong Wind Deaths',    type: 'integer', example: '0' },
    ],
    display: ['district_id', 'fiscal_year', 'flood_deaths', 'fire_deaths', 'house_collapse_deaths'],
  },
};

export const GROUPS = ['Core', 'Demographics', 'Economy', 'Society', 'Environment', 'Safety'];

export const GROUP_COLORS = {
  Core:         '#0A3D91',
  Demographics: '#1251C5',
  Economy:      '#1A7A3C',
  Society:      '#E8B400',
  Environment:  '#25A356',
  Safety:       '#C0392B',
};